---
- name: get role definitions id
  azure.azcollection.azure_rm_roledefinition_info:
    role_name: "{{ item.name }}"
    scope: /
  register: az_rbac_role_definition

- name: assign RBAC roles to {{ az_service_principal.app_display_name }} Service Principal
  azure.azcollection.azure_rm_roleassignment:
    scope: "{{ scp }}"
    assignee_object_id: "{{ az_service_principal.object_id }}"
    role_definition_id: "{{ az_rbac_role_definition.roledefinitions[0].id }}"
  loop: "{{ item.scopes }}"
  loop_control:
    loop_var: scp
  retries: 10
  delay: 30
