---
- name: create {{ az_app_display_name }} Azure AD Service Principal
  azure.azcollection.azure_rm_adserviceprincipal:
    app_id: "{{ az_app_id }}"
    cloud_environment: "{{ az_app_cloud_env }}"
  register: az_sp

- name: set Service Principal variable
  ansible.builtin.set_fact:
    az_service_principal: "{{ az_sp }}"
