---
- name: Get Azure AD Service Principal info
  azure.azcollection.azure_rm_adserviceprincipal_info:
    app_id: "{{ az_app_id }}"
  register: azure_ad_service_principal_existing

- name: Create/update Azure AD Service Principal - {{ az_app_display_name }}
  azure.azcollection.azure_rm_adserviceprincipal:
    app_id: "{{ az_app_id }}"
    cloud_environment: "{{ az_app_cloud_env }}"
  register: az_service_principal_new

- name: Set Azure AD Service Principal object
  ansible.builtin.set_fact:
    az_service_principal: "{{ azure_ad_service_principal_existing.service_principals[0] | default(az_service_principal_new, true) }}"
