---
- name: get role definitions id
  azure.azcollection.azure_rm_roledefinition_info:
    role_name: "{{ item.name }}"
    scope: /
  register: az_rbac_role_definition

- ansible.builtin.include_tasks: tasks/assign_roles.yml
  loop: "{{ item.scopes }}"
  loop_control:
    loop_var: scp
